### ISSUE TITLE
Staff Page has Disappeared 

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/University-Community-Collaborative#11]
Hey do you know why the staff page is gone now? Thanks!

**Comment by lidopaglia** [comment]
Fixed.

Looks like wget got a 503 response from liberalarts.temple.edu when it tried to download profiles.csv. I re-ran the build in travis and it looks good now.

**Comment by CVE82** [comment]
Thank you so much for the info L-Dogg!
