### ISSUE TITLE
Hero Resize

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/University-Community-Collaborative#3]
Hey Zac Attack! When you get a chance can you align the hero image for me so it shows the girls faces? Also can we eliminate the red hue please for this center? Thanks!~

**Comment by ZMcGroarty** [comment]
Not 100% sure how non-hue will work so heres two>

![hero_ucc_nohue](https://user-images.githubusercontent.com/15017242/31182118-0786a5c6-a8f1-11e7-8482-24b4b42ea7e9.png)
![hero_ucc](https://user-images.githubusercontent.com/15017242/31182119-078a3e3e-a8f1-11e7-8176-fbeb7948dcb6.png)

**Comment by CVE82** [comment]
Awesome thank you! i think I am going to use the non hue, it looks great thank you!
