### ISSUE TITLE
UCC Logo on Home Page

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/University-Community-Collaborative#4]
The UCC logo just needs to be embedded within the header (banner). Thanks!

**Comment by CVE82** [comment]
here is the color for the theme #1791ab

**Comment by CVE82** [comment]
Can you please adjust the image size so it's centered? Thanks!

**Comment by ZMcGroarty** [comment]
![hero_ucc_nohue2-min](https://user-images.githubusercontent.com/15017242/31728599-b38d7e80-b3fa-11e7-925a-49bf7684bb4f.png)

**Comment by CVE82** [comment]
Thanks Zac!
