### ISSUE TITLE
Red Hue on Hero Image- Change Please

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/University-Community-Collaborative#6]
Hey Zac attack, can you make the red hue on the hero image this color instead please to match their theme? #1791ab  Thank you!!

**Comment by ZMcGroarty** [comment]
![hero_ucc_bluehue2](https://user-images.githubusercontent.com/15017242/31837567-4c6336a6-b5a7-11e7-8f7b-d80458dee0ff.png)

**Comment by CVE82** [comment]
Hey @ZMcGroarty  I'm sorry I should've clarified, we are going to leave the image as is and I just need the red hue that is on the sides #1791ab (screenshot below)

![image](https://user-images.githubusercontent.com/15130721/31896702-6aee7fee-b7e2-11e7-965c-38e9cc6879b4.png)
